# Generated by Django 5.2 on 2025-04-05 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('starttime', models.DateTimeField(verbose_name='start time')),
                ('endtime', models.DateTimeField(verbose_name='end time')),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('eventlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blossom.show')),
            ],
        ),
        migrations.CreateModel(
            name='ShowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('starttime', models.DateTimeField(verbose_name='start time')),
                ('endtime', models.DateTimeField(verbose_name='end time')),
                ('description', models.TextField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blossom.location')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blossom.show')),
            ],
        ),
    ]
