# Generated by Django 5.2 on 2025-04-02 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('starttime', models.DateTimeField(verbose_name='start time')),
                ('endtime', models.DateTimeField(verbose_name='end time')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('starttime', models.DateTimeField(verbose_name='start time')),
                ('endtime', models.DateTimeField(verbose_name='end time')),
                ('description', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blossom.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='eventlocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blossom.show'),
        ),
    ]
