# Generated by Django 5.2 on 2025-04-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blossom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blossom.show'),
        ),
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blossom.location'),
        ),
    ]
