# Generated by Django 5.2 on 2025-04-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blossom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='eventlocation',
            new_name='show',
        ),
    ]
