# Generated by Django 5.2 on 2025-04-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blossom', '0002_event_show_alter_event_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
